/// SharedPrefrences keys
const String kAppSettingSP = 'APP_SETTING';
const String kDeviceDetailSP = 'DEVICE_DETAIL_LIST';

/// Other constants
const String kAppVersion = '2.9.1';
const String kDefaultDevicePassword = '000000';
const String kDefaultDeviceModel = 'dana';
const String kDefaultDeviceName = 'دستگاه مرکزی 1';
const String kDefaultState = 'نامعلوم';
const int kSMSCooldown = 15;
const String kDefaultAlertTime = '10';
const String kDefaultRelayTrigger = '000002'; //2 second default
const String kZone1Name = 'زون ۱ - سیم دار';
const String kZone2Name = 'زون ۲ - سیم دار';
const String kZone3Name = 'زون ۳ - سیم دار';
const String kZone4Name = 'زون ۴ - سیم دار';
const String kZone5Name = 'زون ۵ - بیسیم';
const String kDefaultZoneType = 'Normaly Close';
const String kContact1Name = 'مخاطب اول - مدیر';
const String kContact2Name = 'مخاطب دوم';
const String kContact3Name = 'مخاطب سوم';
const String kContact4Name = 'مخاطب چهارم';
const String kContact5Name = 'مخاطب پنجم';
const String kContact6Name = 'مخاطب ششم';
const String kContact7Name = 'مخاطب هفتم';
const String kContact8Name = 'مخاطب هشتم';
const String kContact9Name = 'مخاطب نهم';
const String kScenarioName = 'سناریو';
const String kScenario1Name = 'سناریو اول';
const String kScenario2Name = 'سناریو دوم';
const String kScenario3Name = 'سناریو سوم';
const String kScenario4Name = 'سناریو چهارم';
const String kScenario5Name = 'سناریو پنجم';
const String kScenario6Name = 'سناریو ششم';
const String kScenario7Name = 'سناریو هفتم';
const String kScenario8Name = 'سناریو هشتم';
const String kScenario9Name = 'سناریو نهم';
const String kScenario10Name = 'سناریو دهم';